export const metadata = {
  title: "Terms of Service | GenForge",
  description: "Terms and conditions for using GenForge.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white px-6 py-16 md:py-24">
      <div className="mx-auto max-w-2xl">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: 20 April 2026</p>

        <section className="space-y-8 text-gray-700 leading-relaxed text-[15px]">

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Acceptance of terms</h2>
            <p>
              By accessing or using GenForge at{" "}
              <a href="https://trygenforge.com" className="text-indigo-600 underline">trygenforge.com</a>{" "}
              or{" "}
              <a href="https://genforge.co.uk" className="text-indigo-600 underline">genforge.co.uk</a>,
              you agree to be bound by these Terms of Service. If you do not agree, please do not use our service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Description of service</h2>
            <p>
              GenForge provides AI-powered business tools for entrepreneurs and small businesses,
              including free and paid tools for generating business names, taglines, marketing copy,
              and other business content.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Free and paid tools</h2>
            <p>
              Some tools are available free of charge. PRO tools require a one-time payment per use.
              All payments are processed securely by Stripe. Prices are displayed clearly before purchase.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Use of AI-generated content</h2>
            <p>
              Content generated by GenForge tools is produced by AI and provided for informational
              and creative purposes only. You are responsible for reviewing, editing, and verifying
              any content before using it for your business. GenForge does not guarantee the accuracy,
              originality, or suitability of AI-generated content for any specific purpose.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Intellectual property</h2>
            <p>
              You retain ownership of any content you input into GenForge tools. AI-generated outputs
              are provided to you for your personal and commercial use. GenForge retains all rights to
              its platform, design, and underlying technology.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Prohibited use</h2>
            <p>You agree not to use GenForge to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Generate illegal, harmful, or offensive content.</li>
              <li>Attempt to reverse engineer or copy our platform.</li>
              <li>Resell or redistribute GenForge outputs as a standalone product.</li>
              <li>Violate any applicable laws or regulations.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Disclaimer of warranties</h2>
            <p>
              GenForge is provided &quot;as is&quot; without warranties of any kind. We do not guarantee
              uninterrupted or error-free service. AI-generated content may contain inaccuracies
              and should not be relied upon as professional legal, financial, or business advice.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, GenForge shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of our service or
              AI-generated content.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Changes to terms</h2>
            <p>
              We may update these Terms of Service from time to time. Changes will be posted on this
              page with an updated date. Continued use of GenForge after changes constitutes
              acceptance of the revised terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Contact</h2>
            <p>
              For any questions about these terms, contact us at:{" "}
              <a href="mailto:hello@trygenforge.com" className="text-indigo-600 underline">
                hello@trygenforge.com
              </a>
            </p>
          </div>

        </section>
      </div>
    </main>
  );
}